spring:
  application:
    name: chat-mcp-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rag?characterEncoding=utf-8&serverTimezone=GMT%2B8
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 300ms
#  main:
#    web-application-type: none # ????web????
#    banner-mode: off # ??banner
  ai:
    mcp:
       server:
         name: chat-mcp-service # ?????
         version: 1.0.0 # ?????
         sse-message-endpoint: /sse
server:
  port: 8083